services:
  no:
    build: .
    env_file:
      - .env
    ports:
      - "8080:8080"
    environment:
      INSTANCE_ID: 1
      LIDER_ID: 1
      PORTA: 8080
    depends_on:
      - dist_db

  no2:
    build: .
    ports:
      - "8081:8081"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: si_db
      POSTGRES_URL: jdbc:postgresql://leaderelection-dist_db_2-1:5432/$POSTGRES_DB
      URL_RABBIT: amqps://fyjciiwz:rpkq9q8usoSe1fzKBEg8IuOBuRSWKc6b@moose.rmq.cloudamqp.com/fyjciiwz
      QUEUE_NAME: instance-2
      NOTIFY_QUEUE: notify-instance-2
      INSTANCE_ID: 2
      LIDER_ID: 1
      PORTA: 8082
    depends_on:
      - dist_db_2

  no3:
    build: .
    ports:
      - "8083:8083"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: si_db
      POSTGRES_URL: jdbc:postgresql://leaderelection-dist_db_3-1:5432/$POSTGRES_DB
      URL_RABBIT: amqps://fyjciiwz:rpkq9q8usoSe1fzKBEg8IuOBuRSWKc6b@moose.rmq.cloudamqp.com/fyjciiwz
      QUEUE_NAME: instance-3
      NOTIFY_QUEUE: notify-instance-3
      INSTANCE_ID: 3
      LIDER_ID: 1
      PORTA: 8083
    depends_on:
      - dist_db_3

  dist_db:
    image: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"

  dist_db_2:
    image: postgres
    env_file:
      - .env
    ports:
      - "5433:5432"

  dist_db_3:
    image: postgres
    env_file:
      - .env
    ports:
      - "5434:5432"